ALTER TABLE partners
ALTER COLUMN partner_id
ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(
    pg_get_serial_sequence('partners', 'partner_id'),
    COALESCE((SELECT MAX(partner_id) FROM partners), 1),
    EXISTS (SELECT 1 FROM partners)
);
